(function(){
  if(window.__ADMIN_ENTRY__) return;
  const app=document.getElementById('clientApp'); if(!app) return;
  document.body.classList.remove('client-v2'); document.body.classList.add('client-v3');
  let step=1,selectedServices=[],selectedProfessional='auto',selectedDate='',selectedTime='',bookingFilter='upcoming';
  const profileKey='sc_client_profile_v3';
  const getProfile=()=>{try{return JSON.parse(localStorage.getItem(profileKey)||'{}')}catch(e){return {}}};
  const setProfile=p=>localStorage.setItem(profileKey,JSON.stringify(p));
  const initials=n=>(n||'SC').trim().split(/\s+/).slice(0,2).map(x=>x[0]||'').join('').toUpperCase();
  const ids=x=>String(x??'');
  const totalDuration=()=>selectedServices.reduce((s,x)=>s+Number(x.duration||0),0);
  const totalPrice=()=>selectedServices.reduce((s,x)=>s+Number(x.price||0),0);
  const selectedNames=()=>selectedServices.map(x=>x.name).join(' + ');
  function closeDrawer(){document.getElementById('c3Drawer')?.classList.remove('open');document.getElementById('c3Backdrop')?.classList.remove('open')}
  function openDrawer(){document.getElementById('c3Drawer')?.classList.add('open');document.getElementById('c3Backdrop')?.classList.add('open')}
  function shell(active='home'){
    ['c3Header','c3Drawer','c3Backdrop'].forEach(id=>document.getElementById(id)?.remove());
    const p=getProfile(),logged=!!(p.name&&p.phone);
    const h=document.createElement('header');h.id='c3Header';h.className='c3-header';h.innerHTML=`<button class="c3-menu" onclick="c3OpenDrawer()" aria-label="Abrir menu">☰</button><div class="c3-brand"><div class="c3-logo">SC</div><div><strong>Studio Capricho Hair</strong><small>Cuidado e beleza com hora marcada</small></div></div><nav class="c3-nav">${[['home','Início'],['services','Serviços'],['pros','Profissionais'],['bookings','Meus agendamentos'],['profile','Perfil']].map(([id,l])=>`<button class="${active===id?'active':''}" onclick="c3Nav('${id}')">${l}</button>`).join('')}</nav><div class="c3-actions"><button class="c3-account" onclick="c3Nav('profile')">${logged?`${initials(p.name)} • ${p.name.split(' ')[0]}`:'Entrar / Cadastrar'}</button><button class="c3-cta" onclick="c3StartBooking()">Agendar agora</button></div>`;document.body.appendChild(h);
    const bd=document.createElement('div');bd.id='c3Backdrop';bd.className='c3-backdrop';bd.onclick=closeDrawer;document.body.appendChild(bd);
    const d=document.createElement('aside');d.id='c3Drawer';d.className='c3-drawer';d.innerHTML=`${[['home','🏠','Início'],['services','✂️','Serviços'],['pros','👩‍🦰','Profissionais'],['bookings','📅','Meus agendamentos'],['profile','👤','Perfil']].map(([id,i,l])=>`<button class="${active===id?'active':''}" onclick="c3Nav('${id}')"><span>${i}</span>${l}</button>`).join('')}<hr style="border:0;border-top:1px solid #3b3125;margin:8px 0"><button onclick="c3StartBooking()"><span>✨</span>Agendar agora</button>`;document.body.appendChild(d);
  }
  function set(html,active){shell(active);app.innerHTML=html;window.scrollTo({top:0,behavior:'smooth'})}
  function heroImage(){return window.STUDIO_HOME_IMAGE||window.portfolio?.[0]?.image||'assets/trabalho-01.jpg'}
  function mapUrl(){const a=encodeURIComponent(studioProfile?.address||'Jundiaí SP');return `https://www.google.com/maps?q=${a}&output=embed`}
  function renderHome(){const featured=(services||[]).slice(0,4),pros=(professionals||[]).slice(0,4);set(`<section class="c3-hero"><div class="c3-hero-copy"><div class="c3-kicker">Studio Capricho Hair</div><h1>Cuidado e beleza para o seu cabelo, com hora marcada.</h1><p>${studioProfile?.bio||'Atendimento personalizado para valorizar sua beleza e sua autoestima.'}</p><div><button class="c3-cta" onclick="c3StartBooking()">Agendar agora</button></div></div><div class="c3-hero-photo" style="background-image:url('${heroImage()}')"></div></section><section class="c3-quick"><div class="c3-info"><span>📍</span><strong>Endereço</strong><small>${studioProfile?.address||'Jundiaí - SP'}</small></div><div class="c3-info"><span>🕒</span><strong>Funcionamento</strong><small>Atendimento com hora marcada</small></div><div class="c3-info"><span>💬</span><strong>Contato</strong><small>WhatsApp do Studio</small></div><div class="c3-info"><span>⭐</span><strong>Avaliações</strong><small>Área preparada para avaliações reais</small></div></section><section class="c3-section"><div class="c3-section-head"><div><div class="c3-kicker">Mais procurados</div><h2>Serviços em destaque</h2></div><button class="c3-secondary" onclick="c3Nav('services')">Ver todos</button></div><div class="c3-grid">${featured.map(s=>`<div class="c3-card"><div>✨</div><h3>${s.name}</h3><div class="c3-muted">${s.duration} min</div><div class="c3-price">${money(Number(s.price||0))}</div></div>`).join('')}</div></section><section class="c3-section"><div class="c3-section-head"><div><div class="c3-kicker">Equipe</div><h2>Nossos profissionais</h2></div></div><div class="c3-grid">${pros.map(p=>`<div class="c3-card"><div class="c3-avatar">${initials(p.name)}</div><h3>${p.name}</h3><div class="c3-muted">${p.specialty||'Profissional do Studio'}</div></div>`).join('')}</div></section><section class="c3-section c3-footer-grid"><div class="c3-panel"><strong>Localização</strong><iframe class="c3-map" loading="lazy" referrerpolicy="no-referrer-when-downgrade" src="${mapUrl()}"></iframe></div><div class="c3-panel"><strong>Formas de pagamento</strong><p class="c3-muted">PIX • Dinheiro • Cartão</p></div><div class="c3-panel"><strong>Política de cancelamento</strong><p class="c3-muted">Cancelamentos e remarcações devem respeitar a política informada pelo Studio.</p></div></section>`,'home')}
  function renderServices(){const groups={};(services||[]).forEach(s=>{const c=s.category||'Serviços';(groups[c]||(groups[c]=[])).push(s)});set(`<section class="c3-section"><div class="c3-kicker">Catálogo</div><h2>Serviços</h2><p class="c3-muted">Conheça os serviços disponíveis e agende em poucos passos.</p>${Object.entries(groups).map(([cat,list])=>`<div style="margin-top:22px"><h3>${cat}</h3><div class="c3-grid">${list.map(s=>`<div class="c3-card"><div>✨</div><h3>${s.name}</h3><div class="c3-muted">Duração aproximada: ${s.duration} min</div><div class="c3-price">${money(Number(s.price||0))}</div><button class="c3-primary" style="width:100%;margin-top:12px" onclick="c3StartWithService('${s.id}')">Agendar este serviço</button></div>`).join('')}</div></div>`).join('')}</section>`,'services')}
  function renderPros(){set(`<section class="c3-section"><div class="c3-kicker">Equipe</div><h2>Profissionais</h2><div class="c3-grid" style="margin-top:16px">${(professionals||[]).map(p=>`<div class="c3-card"><div class="c3-avatar">${initials(p.name)}</div><h3>${p.name}</h3><div class="c3-muted">${p.specialty||'Profissional do Studio'}</div></div>`).join('')}</div></section>`,'pros')}
  function stepper(){return `<div class="c3-stepper"><div class="c3-step-head"><strong>Passo ${step} de 4</strong><span>${['Serviço','Profissional','Data e horário','Confirmação'][step-1]}</span></div><div class="c3-progress"><span style="width:${step*25}%"></span></div></div>`}
  function bottom(can=true){return `<div class="c3-bottom">${step>1?'<button class="c3-secondary" onclick="c3Back()">Voltar</button>':''}<button class="c3-primary" ${can?'':'disabled'} onclick="c3Next()">${step===4?'Confirmar agendamento':'Continuar'}</button></div>`}
  function serviceCard(s){const sel=selectedServices.some(x=>ids(x.id)===ids(s.id));return `<div class="c3-card clickable ${sel?'selected':''}" data-name="${(s.name||'').toLowerCase()}" data-category="${(s.category||'serviços').toLowerCase()}" onclick="c3ToggleService('${s.id}')"><div class="c3-check">✓</div><h3>${s.name}</h3><div class="c3-muted">${s.category||'Serviço'} • ${s.duration} min</div><div class="c3-price">${money(Number(s.price||0))}</div></div>`}
  function dateButtons(){let out='';const base=new Date();for(let i=0;i<21;i++){const d=new Date(base);d.setDate(base.getDate()+i);const iso=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,dow=d.getDay(),disabled=dow===0||dow===1;out+=`<button class="c3-date ${selectedDate===iso?'selected':''}" ${disabled?'disabled':''} onclick="c3SelectDate('${iso}')"><small>${d.toLocaleDateString('pt-BR',{weekday:'short'})}</small><br>${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}</button>`}return out}
  function renderBooking(){shell('book');const duration=totalDuration(),price=totalPrice();let html='';if(step===1){const cats=[...new Set((services||[]).map(s=>s.category||'Serviços'))];html=`${stepper()}<section class="c3-book-shell"><div class="c3-kicker">Etapa 1</div><h1 class="c3-title">Escolha o serviço</h1><p class="c3-muted">Você pode selecionar mais de um serviço.</p><div class="c3-search-row"><input id="c3Search" placeholder="Buscar por nome" oninput="c3FilterServices()"><select id="c3Category" onchange="c3FilterServices()"><option value="">Todas as categorias</option>${cats.map(c=>`<option>${c}</option>`).join('')}</select></div><div id="c3ServiceGrid" class="c3-service-grid">${(services||[]).map(serviceCard).join('')}</div>${selectedServices.length?`<div class="c3-selection-summary"><div><strong>${selectedServices.length} serviço(s)</strong><div style="font-size:11px;color:#cfc7bd">${duration} min no total</div></div><strong>${money(price)}</strong></div>`:''}${bottom(selectedServices.length>0)}</section>`}
    if(step===2){html=`${stepper()}<section class="c3-book-shell"><div class="c3-kicker">Etapa 2</div><h1 class="c3-title">Escolha o profissional</h1><p class="c3-muted">Selecione um profissional ou deixe o Studio escolher automaticamente.</p><div class="c3-pro-grid" style="margin-top:14px"><div class="c3-card clickable ${selectedProfessional==='auto'?'selected':''}" onclick="c3PickPro('auto')"><div class="c3-avatar">✨</div><h3>Sem preferência</h3><div class="c3-muted">Atribuição automática conforme disponibilidade.</div></div>${(professionals||[]).map(p=>`<div class="c3-card clickable ${ids(selectedProfessional)===ids(p.id)?'selected':''}" onclick="c3PickPro('${p.id}')"><div class="c3-avatar">${initials(p.name)}</div><h3>${p.name}</h3><div class="c3-muted">${p.specialty||'Profissional do Studio'}</div></div>`).join('')}</div>${bottom(!!selectedProfessional)}</section>`}
    if(step===3){const prof=selectedProfessional==='auto'?(professionals||[])[0]:(professionals||[]).find(p=>ids(p.id)===ids(selectedProfessional));html=`${stepper()}<section class="c3-book-shell"><div class="c3-kicker">Etapa 3</div><h1 class="c3-title">Data e horário</h1><p class="c3-muted">Dias sem atendimento ficam desabilitados. Horários ocupados aparecem indisponíveis.</p><div class="c3-calendar" style="margin-top:14px"><div class="c3-date-row">${dateButtons()}</div>${selectedDate?`<div class="c3-times">${(times||[]).map(t=>{const free=prof&&typeof isSlotFree==='function'?isSlotFree(selectedDate,prof.id,t,duration):true;return `<button class="c3-time ${selectedTime===t?'selected':''}" ${free?'':'disabled'} onclick="c3SelectTime('${t}')">${t}</button>`}).join('')}</div>`:''}${selectedTime?`<p class="c3-muted" style="margin:13px 0 0">Duração total: <strong>${duration} min</strong> • Término previsto: <strong>${addMinutes(selectedTime,duration)}</strong></p>`:''}</div>${bottom(!!selectedDate&&!!selectedTime)}</section>`}
    if(step===4){const p=getProfile(),prof=selectedProfessional==='auto'?(professionals||[])[0]:(professionals||[]).find(x=>ids(x.id)===ids(selectedProfessional));html=`${stepper()}<section class="c3-book-shell"><div class="c3-kicker">Etapa 4</div><h1 class="c3-title">Confirme seu agendamento</h1><div class="c3-summary" style="margin-top:14px"><div class="c3-summary-line"><span>Serviço(s)</span><strong>${selectedNames()}</strong></div><div class="c3-summary-line"><span>Profissional</span><strong>${selectedProfessional==='auto'?'Sem preferência':prof?.name||'-'}</strong></div><div class="c3-summary-line"><span>Data</span><strong>${fmtDate(selectedDate)}</strong></div><div class="c3-summary-line"><span>Horário</span><strong>${selectedTime}–${addMinutes(selectedTime,duration)}</strong></div><div class="c3-summary-line"><span>Duração</span><strong>${duration} min</strong></div><div class="c3-summary-line"><span>Valor total</span><strong>${money(price)}</strong></div></div><div class="c3-panel c3-form" style="margin-top:12px"><label>Nome</label><input id="c3Name" value="${p.name||''}" placeholder="Seu nome"><label>WhatsApp</label><input id="c3Phone" value="${p.phone||localStorage.getItem('sc_last_phone')||''}" placeholder="(11) 99999-9999"><label>Observações (opcional)</label><textarea id="c3Notes" rows="3" placeholder="Ex.: alergia a algum produto"></textarea><label>Forma de pagamento</label><select id="c3Payment"><option>Pagar no local</option><option>PIX</option><option>Cartão</option></select><label class="c3-policy"><input id="c3Policy" type="checkbox"><span>Li e aceito a política de cancelamento do Studio.</span></label></div>${bottom(true)}</section>`}
    app.innerHTML=html;window.scrollTo({top:0,behavior:'smooth'})
  }
  async function finish(){const name=document.getElementById('c3Name')?.value.trim(),phone=document.getElementById('c3Phone')?.value.trim(),policy=document.getElementById('c3Policy')?.checked;if(!name||!phone)return toast('Informe seu nome e WhatsApp.');if(!policy)return toast('Aceite a política de cancelamento para continuar.');const duration=totalDuration(),prof=selectedProfessional==='auto'?(professionals||[])[0]:(professionals||[]).find(p=>ids(p.id)===ids(selectedProfessional));if(!prof)return toast('Nenhum profissional disponível.');if(typeof isSlotFree==='function'&&!isSlotFree(selectedDate,prof.id,selectedTime,duration))return toast('Este horário acabou de ser reservado. Escolha outro.');const booking={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),clientName:name,phone,serviceId:selectedServices[0]?.id,serviceName:selectedNames(),professionalId:prof.id,professionalName:prof.name,date:selectedDate,time:selectedTime,endTime:addMinutes(selectedTime,duration),price:totalPrice(),status:'pendente',createdAt:new Date().toISOString(),notes:document.getElementById('c3Notes')?.value.trim()||'',paymentMethod:document.getElementById('c3Payment')?.value||'Pagar no local'};const cloud=typeof cloudCreateBooking==='function'?await cloudCreateBooking(booking):{ok:true};if(!cloud.ok)return toast('Não foi possível reservar este horário. Escolha outro.');if(cloud.id)booking.id=cloud.id;const all=getBookings();all.push(booking);saveBookings(all);localStorage.setItem('sc_last_phone',phone);const old=getProfile();setProfile({...old,name,phone});renderSuccess(booking)}
  function renderSuccess(b){set(`<section class="c3-book-shell"><div class="c3-success"><div class="c3-success-icon">✓</div><div class="c3-kicker">Solicitação enviada</div><h1 class="c3-title">Agendamento recebido!</h1><p class="c3-muted">O Studio irá confirmar seu horário.</p><div class="c3-summary" style="text-align:left;margin-top:18px"><div class="c3-summary-line"><span>Serviço(s)</span><strong>${b.serviceName}</strong></div><div class="c3-summary-line"><span>Data</span><strong>${fmtDate(b.date)}</strong></div><div class="c3-summary-line"><span>Horário</span><strong>${b.time}</strong></div></div><div class="c3-bottom" style="position:static"><button class="c3-secondary" onclick="c3AddCalendar('${b.id}')">Adicionar ao calendário</button><button class="c3-primary" onclick="c3Nav('bookings')">Ver meus agendamentos</button></div></div></section>`,'bookings')}
  function mine(){const p=getProfile(),phone=p.phone||localStorage.getItem('sc_last_phone')||'';return getBookings().filter(b=>!phone||b.phone===phone).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time))}
  function apptCard(b){const [y,m,d]=b.date.split('-'),future=b.date>=new Date().toISOString().slice(0,10)&&!['cancelado','recusado','concluido'].includes(b.status);return `<div class="c3-appointment"><div class="c3-datebox"><small>${m}/${y}</small><strong>${d}</strong><span>${b.time}</span></div><div><strong>${b.serviceName}</strong><div class="c3-muted">${b.professionalName||''}</div>${future?`<div class="c3-appt-actions"><button onclick="c3Rebook('${b.id}')">Remarcar</button><button onclick="c3AskCancel('${b.id}')">Cancelar</button><button onclick="c3Detail('${b.id}')">Ver detalhes</button></div>`:`<div class="c3-appt-actions"><button onclick="c3Detail('${b.id}')">Ver detalhes</button></div>`}</div><span class="c3-status ${b.status}">${typeof statusLabel==='function'?statusLabel(b.status):b.status}</span></div>`}
  function renderBookings(){const all=mine(),today=new Date().toISOString().slice(0,10),up=all.filter(b=>b.date>=today&&!['cancelado','recusado','concluido'].includes(b.status)),hist=all.filter(b=>b.date<today||['cancelado','recusado','concluido'].includes(b.status)),items=bookingFilter==='history'?hist:up;set(`<section class="c3-section"><div class="c3-kicker">Sua agenda</div><h2>Meus agendamentos</h2><div class="c3-tabs"><button class="${bookingFilter==='upcoming'?'active':''}" onclick="c3BookingTab('upcoming')">Próximos</button><button class="${bookingFilter==='history'?'active':''}" onclick="c3BookingTab('history')">Histórico</button></div><div>${items.length?items.map(apptCard).join(''):`<div class="c3-empty"><strong>${bookingFilter==='upcoming'?'Você não tem agendamentos futuros.':'Nenhum atendimento no histórico.'}</strong>${bookingFilter==='upcoming'?'<p>Escolha seu próximo cuidado com poucos toques.</p><button class="c3-cta" onclick="c3StartBooking()">Agendar agora</button>':''}</div>`}</div></section>`,'bookings')}
  function profileStats(phone){const x=getBookings().filter(b=>b.phone===phone&&b.status==='concluido');const spent=x.reduce((s,b)=>s+Number(b.price||0),0),counts={};x.forEach(b=>counts[b.serviceName]=(counts[b.serviceName]||0)+1);const fav=Object.entries(counts).sort((a,b)=>b[1]-a[1])[0]?.[0]||'-';return {visits:x.length,spent,fav}}
  function renderProfile(){const p=getProfile(),st=profileStats(p.phone||'');set(`<section class="c3-section" style="max-width:900px;margin-inline:auto"><div class="c3-kicker">Conta</div><h2>Perfil do cliente</h2><div class="c3-profile-grid" style="margin-top:16px"><div class="c3-panel c3-form"><label>Nome</label><input id="c3ProfName" value="${p.name||''}" placeholder="Seu nome"><label>Telefone</label><input id="c3ProfPhone" value="${p.phone||''}" placeholder="Seu WhatsApp"><label>E-mail</label><input id="c3ProfEmail" type="email" value="${p.email||''}" placeholder="voce@email.com"><label>Data de nascimento</label><input id="c3ProfBirth" type="date" value="${p.birth||''}"><label>Profissional favorito</label><select id="c3ProfFav"><option value="">Sem preferência</option>${(professionals||[]).map(x=>`<option value="${x.id}" ${ids(p.favoriteProfessional)===ids(x.id)?'selected':''}>${x.name}</option>`).join('')}</select><label>Observações permanentes</label><textarea id="c3ProfNotes" rows="3" placeholder="Ex.: alergias ou preferências">${p.notes||''}</textarea><button class="c3-primary" style="width:100%;margin-top:15px" onclick="c3SaveProfile()">Salvar perfil</button><p class="c3-muted">Este perfil fica salvo neste dispositivo. Login seguro por senha ou código requer ativação do módulo de autenticação no Supabase.</p></div><div><div class="c3-panel"><div class="c3-avatar" style="width:68px;height:68px;font-size:20px">${initials(p.name)}</div><h3>${p.name||'Visitante'}</h3><div class="c3-stats"><div class="c3-stat"><small>Visitas</small><strong>${st.visits}</strong></div><div class="c3-stat"><small>Total gasto</small><strong>${money(st.spent)}</strong></div></div><p class="c3-muted">Serviço mais realizado: <strong>${st.fav}</strong></p><button class="c3-secondary" style="width:100%;margin-top:8px" onclick="c3Logout()">Sair / limpar perfil</button><button class="c3-secondary" style="width:100%;margin-top:8px;color:#9a4141" onclick="c3DeleteProfile()">Excluir dados deste dispositivo</button></div></div></div></section>`,'profile')}
  function modal(title,body,actions){let m=document.getElementById('c3Modal');if(!m){m=document.createElement('div');m.id='c3Modal';m.className='c3-modal';document.body.appendChild(m)}m.innerHTML=`<div class="c3-modal-card"><h3>${title}</h3>${body}<div class="c3-bottom" style="position:static;margin-bottom:0">${actions}</div></div>`;m.classList.add('open')}
  function closeModal(){document.getElementById('c3Modal')?.classList.remove('open')}
  window.c3OpenDrawer=openDrawer;window.c3CloseDrawer=closeDrawer;window.c3Nav=v=>{closeDrawer();if(v==='home')renderHome();if(v==='services')renderServices();if(v==='pros')renderPros();if(v==='bookings')renderBookings();if(v==='profile')renderProfile()};
  window.c3StartBooking=()=>{step=1;selectedServices=[];selectedProfessional='auto';selectedDate='';selectedTime='';renderBooking()};
  window.c3StartWithService=id=>{const s=(services||[]).find(x=>ids(x.id)===ids(id));selectedServices=s?[s]:[];selectedProfessional='auto';selectedDate='';selectedTime='';step=2;renderBooking()};
  window.c3ToggleService=id=>{const s=(services||[]).find(x=>ids(x.id)===ids(id));if(!s)return;const i=selectedServices.findIndex(x=>ids(x.id)===ids(id));if(i>=0)selectedServices.splice(i,1);else selectedServices.push(s);renderBooking()};
  window.c3FilterServices=()=>{const q=(document.getElementById('c3Search')?.value||'').toLowerCase(),cat=(document.getElementById('c3Category')?.value||'').toLowerCase();document.querySelectorAll('#c3ServiceGrid .c3-card').forEach(x=>x.style.display=(!q||x.dataset.name.includes(q))&&(!cat||x.dataset.category===cat)?'':'none')};
  window.c3PickPro=id=>{selectedProfessional=id;renderBooking()};window.c3SelectDate=d=>{selectedDate=d;selectedTime='';renderBooking()};window.c3SelectTime=t=>{selectedTime=t;renderBooking()};window.c3Back=()=>{if(step>1){step--;renderBooking()}};window.c3Next=async()=>{if(step===1&&!selectedServices.length)return toast('Escolha pelo menos um serviço.');if(step===2&&!selectedProfessional)return toast('Escolha um profissional.');if(step===3&&(!selectedDate||!selectedTime))return toast('Escolha a data e o horário.');if(step<4){step++;renderBooking();return}await finish()};
  window.c3BookingTab=t=>{bookingFilter=t;renderBookings()};window.c3Rebook=id=>{closeModal();c3StartBooking();toast('Escolha os novos detalhes do agendamento.')};
  window.c3AskCancel=id=>modal('Cancelar agendamento','<p class="c3-muted">Confirme o cancelamento. O pedido deve respeitar a política de cancelamento do Studio.</p>',`<button class="c3-secondary" onclick="c3CloseModal()">Voltar</button><button class="c3-primary" style="background:#8f3f48;color:white" onclick="c3Cancel('${id}')">Confirmar cancelamento</button>`);
  window.c3Cancel=async id=>{closeModal();if(typeof setBookingStatus==='function'){await setBookingStatus(id,'cancelado')}else{const all=getBookings(),b=all.find(x=>ids(x.id)===ids(id));if(b)b.status='cancelado';saveBookings(all)}renderBookings();toast('Agendamento cancelado.')};
  window.c3Detail=id=>{const b=getBookings().find(x=>ids(x.id)===ids(id));if(!b)return;modal('Detalhes do agendamento',`<div class="c3-summary"><div class="c3-summary-line"><span>Serviço</span><strong>${b.serviceName}</strong></div><div class="c3-summary-line"><span>Profissional</span><strong>${b.professionalName||'-'}</strong></div><div class="c3-summary-line"><span>Data</span><strong>${fmtDate(b.date)}</strong></div><div class="c3-summary-line"><span>Horário</span><strong>${b.time}</strong></div><div class="c3-summary-line"><span>Status</span><strong>${typeof statusLabel==='function'?statusLabel(b.status):b.status}</strong></div></div>`,`<button class="c3-primary" onclick="c3CloseModal()">Fechar</button>`)};
  window.c3CloseModal=closeModal;window.c3SaveProfile=()=>{const p={name:document.getElementById('c3ProfName').value.trim(),phone:document.getElementById('c3ProfPhone').value.trim(),email:document.getElementById('c3ProfEmail').value.trim(),birth:document.getElementById('c3ProfBirth').value,favoriteProfessional:document.getElementById('c3ProfFav').value,notes:document.getElementById('c3ProfNotes').value.trim()};setProfile(p);if(p.phone)localStorage.setItem('sc_last_phone',p.phone);renderProfile();toast('Perfil salvo neste dispositivo.')};
  window.c3Logout=()=>{localStorage.removeItem(profileKey);renderProfile();toast('Perfil local removido.')};window.c3DeleteProfile=()=>{if(confirm('Excluir os dados do perfil salvos neste dispositivo?')){localStorage.removeItem(profileKey);renderProfile()}};
  window.c3AddCalendar=id=>{const b=getBookings().find(x=>ids(x.id)===ids(id));if(!b)return;const start=(b.date.replaceAll('-','')+'T'+b.time.replace(':','')+'00'),end=(b.date.replaceAll('-','')+'T'+(b.endTime||addMinutes(b.time,60)).replace(':','')+'00'),ics=`BEGIN:VCALENDAR\nVERSION:2.0\nBEGIN:VEVENT\nDTSTART:${start}\nDTEND:${end}\nSUMMARY:Studio Capricho - ${b.serviceName}\nLOCATION:${studioProfile?.address||''}\nEND:VEVENT\nEND:VCALENDAR`;const a=document.createElement('a');a.href='data:text/calendar;charset=utf-8,'+encodeURIComponent(ics);a.download='studio-capricho.ics';a.click()};
  renderHome();
})();