(function(){
  if(window.__ADMIN_ENTRY__) return;
  document.body.classList.add('client-v2');
  const app=document.getElementById('clientApp'); if(!app) return;
  let step=1,selectedService=null,selectedProfessional=null,selectedDate=null,selectedTime=null;
  const lastPhone=localStorage.getItem('sc_last_phone')||'';
  const initials=n=>(n||'SC').split(/\s+/).slice(0,2).map(x=>x[0]).join('').toUpperCase();
  function openDrawer(){document.getElementById('cv2Drawer')?.classList.add('open');document.getElementById('cv2Backdrop')?.classList.add('open')}
  function closeDrawer(){document.getElementById('cv2Drawer')?.classList.remove('open');document.getElementById('cv2Backdrop')?.classList.remove('open')}
  function nav(view){closeDrawer(); if(view==='home')renderHome(); if(view==='services')renderServicesPage(); if(view==='pros')renderProfessionalsPage(); if(view==='bookings')renderMyAppointments(); if(view==='profile')renderProfile(); if(view==='book')startBooking();}
  window.cv2Nav=nav; window.cv2OpenDrawer=openDrawer; window.cv2CloseDrawer=closeDrawer;
  function shell(active='home'){
    document.getElementById('cv2Header')?.remove();document.getElementById('cv2Drawer')?.remove();document.getElementById('cv2Backdrop')?.remove();
    const h=document.createElement('div');h.id='cv2Header';h.className='cv2-header';h.innerHTML=`<button class="cv2-menu-btn" onclick="cv2OpenDrawer()">☰</button><div class="cv2-brand"><div class="cv2-logo">SC</div><div><strong>Studio Capricho Hair</strong><small>Cuidado e beleza com hora marcada</small></div></div><nav class="cv2-desktop-nav">${[['home','Início'],['services','Serviços'],['pros','Profissionais'],['bookings','Meus agendamentos'],['profile','Perfil']].map(([id,l])=>`<button class="${active===id?'active':''}" onclick="cv2Nav('${id}')">${l}</button>`).join('')}</nav><div class="cv2-actions"><button class="cv2-login" onclick="cv2Nav('profile')">Entrar / Cadastrar</button><button class="cv2-cta" onclick="cv2Nav('book')">Agendar agora</button></div>`;document.body.appendChild(h);
    const b=document.createElement('div');b.id='cv2Backdrop';b.className='cv2-backdrop';b.onclick=closeDrawer;document.body.appendChild(b);
    const d=document.createElement('aside');d.id='cv2Drawer';d.className='cv2-drawer';d.innerHTML=`${[['home','🏠','Início'],['services','✂️','Serviços'],['pros','👩‍🦰','Profissionais'],['bookings','📅','Meus agendamentos'],['profile','👤','Perfil']].map(([id,i,l])=>`<button class="${active===id?'active':''}" onclick="cv2Nav('${id}')"><span>${i}</span>${l}</button>`).join('')}<hr style="border:0;border-top:1px solid #3f3529;margin:10px 0"><button onclick="cv2Nav('book')"><span>✨</span>Agendar agora</button>`;document.body.appendChild(d);
  }
  function set(html,active){shell(active);app.innerHTML=html;window.scrollTo({top:0,behavior:'smooth'});}
  function heroImage(){return window.STUDIO_HOME_IMAGE||portfolio?.[0]?.image||'assets/trabalho-01.jpg'}
  function renderHome(){
    const featured=services.slice(0,4),pros=professionals.slice(0,4);
    set(`<section class="cv2-hero"><div class="cv2-hero-copy"><div class="cv2-kicker">Studio Capricho Hair</div><h1>Cuidado e beleza para o seu cabelo, com hora marcada.</h1><p>${studioProfile.bio||'Atendimento personalizado para valorizar sua beleza e sua autoestima.'}</p><div><button class="cv2-cta" onclick="cv2Nav('book')">Agendar agora</button></div></div><div class="cv2-hero-photo" style="background-image:url('${heroImage()}')"></div></section>
    <section class="cv2-quickinfo"><div class="cv2-info"><span>📍</span><strong>Localização</strong><small>${studioProfile.address||'Jundiaí - SP'}</small></div><div class="cv2-info"><span>🕒</span><strong>Atendimento</strong><small>Com hora marcada</small></div><div class="cv2-info"><span>💬</span><strong>Contato</strong><small>WhatsApp do Studio</small></div><div class="cv2-info"><span>⭐</span><strong>Atendimento personalizado</strong><small>Experiência pensada para cada cliente</small></div></section>
    <section class="cv2-section"><div class="cv2-section-head"><div><div class="cv2-kicker">Mais procurados</div><h2>Serviços em destaque</h2></div><button class="cv2-back" style="padding:10px 14px;border-radius:12px" onclick="cv2Nav('services')">Ver todos</button></div><div class="cv2-grid">${featured.map(s=>`<div class="cv2-card"><div>✨</div><h3>${s.name}</h3><div class="cv2-muted">${s.duration} min</div><div class="cv2-price">${money(s.price)}</div></div>`).join('')}</div></section>
    <section class="cv2-section"><div class="cv2-section-head"><div><div class="cv2-kicker">Equipe</div><h2>Nossos profissionais</h2></div></div><div class="cv2-grid">${pros.map(p=>`<div class="cv2-card"><div class="cv2-avatar">${initials(p.name)}</div><h3>${p.name}</h3><div class="cv2-muted">${p.specialty||'Profissional do Studio'}</div></div>`).join('')}</div></section>
    <section class="cv2-section"><div class="cv2-card"><strong>Formas de pagamento</strong><div class="cv2-muted" style="margin-top:7px">PIX • Dinheiro • Cartão</div><hr style="border:0;border-top:1px solid #eee2d2;margin:14px 0"><strong>Política de cancelamento</strong><div class="cv2-muted" style="margin-top:7px">Consulte o Studio para cancelamentos ou alterações de horário.</div></div></section>`, 'home');
  }
  function renderServicesPage(){set(`<section class="cv2-section"><div class="cv2-kicker">Catálogo</div><h2>Serviços</h2><p class="cv2-muted">Escolha o cuidado ideal para você.</p><div class="cv2-grid" style="margin-top:18px">${services.map(s=>`<div class="cv2-card"><div>✨</div><h3>${s.name}</h3><div class="cv2-muted">Duração aproximada: ${s.duration} min</div><div class="cv2-price">${money(s.price)}</div><button class="cv2-next" style="margin-top:14px;width:100%;min-height:42px;border-radius:12px" onclick="cv2ChooseService('${s.id}')">Agendar este serviço</button></div>`).join('')}</div></section>`,'services')}
  window.cv2ChooseService=id=>{selectedService=services.find(s=>String(s.id)===String(id));step=2;renderBooking();}
  function renderProfessionalsPage(){set(`<section class="cv2-section"><div class="cv2-kicker">Equipe</div><h2>Profissionais</h2><div class="cv2-grid" style="margin-top:18px">${professionals.map(p=>`<div class="cv2-card"><div class="cv2-avatar">${initials(p.name)}</div><h3>${p.name}</h3><div class="cv2-muted">${p.specialty||'Profissional do Studio'}</div></div>`).join('')}</div></section>`,'pros')}
  function startBooking(){step=1;selectedService=null;selectedProfessional=null;selectedDate=null;selectedTime=null;renderBooking();}
  function progress(){return `<div class="cv2-progress"><div class="cv2-progress-top"><strong>Passo ${step} de 4</strong><span>${['Serviço','Profissional','Data e horário','Confirmação'][step-1]}</span></div><div class="cv2-progress-track"><div class="cv2-progress-fill" style="width:${step*25}%"></div></div></div>`}
  function bookingFooter(canNext=true){return `<div class="cv2-bottom-actions">${step>1?`<button class="cv2-back" onclick="cv2BackStep()">Voltar</button>`:''}<button class="cv2-next" ${canNext?'':'disabled'} onclick="cv2NextStep()">${step===4?'Confirmar agendamento':'Continuar'}</button></div>`}
  window.cv2BackStep=()=>{if(step>1){step--;renderBooking()}};
  window.cv2NextStep=async()=>{if(step===1&&!selectedService)return toast('Escolha um serviço.');if(step===2&&!selectedProfessional)return toast('Escolha um profissional.');if(step===3&&(!selectedDate||!selectedTime))return toast('Escolha a data e o horário.');if(step<4){step++;renderBooking();return;}await finishBooking();}
  function dateButtons(){let out='';const base=new Date();for(let i=0;i<14;i++){const d=new Date(base);d.setDate(base.getDate()+i);const iso=d.toISOString().slice(0,10),dow=d.getDay(),disabled=dow===0||dow===1;out+=`<button class="cv2-date-btn ${selectedDate===iso?'selected':''}" ${disabled?'disabled':''} onclick="cv2SelectDate('${iso}')"><small>${d.toLocaleDateString('pt-BR',{weekday:'short'})}</small><br>${String(d.getDate()).padStart(2,'0')}/${String(d.getMonth()+1).padStart(2,'0')}</button>`}return out}
  window.cv2SelectDate=iso=>{selectedDate=iso;selectedTime=null;renderBooking()};window.cv2SelectTime=t=>{selectedTime=t;renderBooking()};
  function renderBooking(){shell('book');let body='';
    if(step===1) body=`${progress()}<div class="cv2-step-shell"><div class="cv2-kicker">Etapa 1</div><h1 class="cv2-step-title">Escolha o serviço</h1><p class="cv2-muted">Selecione o serviço que deseja agendar.</p><input class="cv2-search" id="cv2Search" placeholder="Buscar serviço" oninput="cv2FilterServices(this.value)"><div id="cv2ServiceGrid" class="cv2-service-grid">${services.map(s=>serviceCard(s)).join('')}</div>${bookingFooter(!!selectedService)}</div>`;
    if(step===2) body=`${progress()}<div class="cv2-step-shell"><div class="cv2-kicker">Etapa 2</div><h1 class="cv2-step-title">Escolha o profissional</h1><p class="cv2-muted">Selecione quem fará seu atendimento.</p><div class="cv2-pro-grid"><div class="cv2-card clickable ${selectedProfessional==='auto'?'selected':''}" onclick="cv2PickPro('auto')"><div class="cv2-avatar">✨</div><h3>Sem preferência</h3><div class="cv2-muted">O Studio define o profissional disponível.</div></div>${professionals.map(p=>`<div class="cv2-card clickable ${selectedProfessional===p.id?'selected':''}" onclick="cv2PickPro('${p.id}')"><div class="cv2-avatar">${initials(p.name)}</div><h3>${p.name}</h3><div class="cv2-muted">${p.specialty||''}</div></div>`).join('')}</div>${bookingFooter(!!selectedProfessional)}</div>`;
    if(step===3){const prof=selectedProfessional==='auto'?professionals[0]:professionals.find(p=>String(p.id)===String(selectedProfessional));const duration=selectedService?.duration||60;body=`${progress()}<div class="cv2-step-shell"><div class="cv2-kicker">Etapa 3</div><h1 class="cv2-step-title">Data e horário</h1><p class="cv2-muted">Escolha um dia disponível e depois um horário livre.</p><div class="cv2-calendar"><div class="cv2-date-row">${dateButtons()}</div>${selectedDate?`<div class="cv2-time-grid">${times.map(t=>{const free=isSlotFree(selectedDate,prof?.id,t,duration);return `<button class="cv2-time-btn ${selectedTime===t?'selected':''}" ${free?'':'disabled'} onclick="cv2SelectTime('${t}')">${t}</button>`}).join('')}</div>`:''}${selectedTime?`<div class="cv2-muted" style="margin-top:14px">Término previsto: <strong>${addMinutes(selectedTime,duration)}</strong></div>`:''}</div>${bookingFooter(!!selectedDate&&!!selectedTime)}</div>`}
    if(step===4){const prof=selectedProfessional==='auto'?professionals[0]:professionals.find(p=>String(p.id)===String(selectedProfessional));body=`${progress()}<div class="cv2-step-shell"><div class="cv2-kicker">Etapa 4</div><h1 class="cv2-step-title">Confirme seu agendamento</h1><div class="cv2-summary"><div class="cv2-summary-line"><span>Serviço</span><strong>${selectedService.name}</strong></div><div class="cv2-summary-line"><span>Profissional</span><strong>${selectedProfessional==='auto'?'Sem preferência':prof?.name}</strong></div><div class="cv2-summary-line"><span>Data</span><strong>${fmtDate(selectedDate)}</strong></div><div class="cv2-summary-line"><span>Horário</span><strong>${selectedTime}–${addMinutes(selectedTime,selectedService.duration)}</strong></div><div class="cv2-summary-line"><span>Valor</span><strong>${money(selectedService.price)}</strong></div></div><div class="cv2-form" style="margin-top:16px"><label>Seu nome</label><input id="cv2Name" placeholder="Nome completo"><label>WhatsApp</label><input id="cv2Phone" value="${lastPhone}" placeholder="(11) 99999-9999"><label>Observações (opcional)</label><textarea id="cv2Notes" rows="3" placeholder="Ex.: alergia a algum produto"></textarea><label>Forma de pagamento</label><select id="cv2Payment"><option>Pagar no local</option><option>PIX</option><option>Cartão</option></select><label class="cv2-policy"><input id="cv2Policy" type="checkbox"> <span>Li e aceito a política de cancelamento do Studio.</span></label></div>${bookingFooter(true)}</div>`}
    app.innerHTML=body;window.scrollTo({top:0,behavior:'smooth'});
  }
  function serviceCard(s){return `<div class="cv2-card clickable ${selectedService?.id===s.id?'selected':''}" data-service-name="${s.name.toLowerCase()}" onclick="cv2PickService('${s.id}')"><h3>${s.name}</h3><div class="cv2-muted">${s.duration} min</div><div class="cv2-price">${money(s.price)}</div></div>`}
  window.cv2PickService=id=>{selectedService=services.find(s=>String(s.id)===String(id));renderBooking()};window.cv2PickPro=id=>{selectedProfessional=id;renderBooking()};window.cv2FilterServices=q=>document.querySelectorAll('#cv2ServiceGrid .cv2-card').forEach(x=>x.style.display=x.dataset.serviceName.includes(q.toLowerCase())?'':'none');
  async function finishBooking(){const name=document.getElementById('cv2Name')?.value.trim(),phone=document.getElementById('cv2Phone')?.value.trim(),policy=document.getElementById('cv2Policy')?.checked;if(!name||!phone)return toast('Informe seu nome e WhatsApp.');if(!policy)return toast('Aceite a política de cancelamento para continuar.');const prof=selectedProfessional==='auto'?professionals[0]:professionals.find(p=>String(p.id)===String(selectedProfessional));if(!isSlotFree(selectedDate,prof.id,selectedTime,selectedService.duration))return toast('Este horário acabou de ser reservado. Escolha outro.');const booking={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),clientName:name,phone,serviceId:selectedService.id,serviceName:selectedService.name,professionalId:prof.id,professionalName:prof.name,date:selectedDate,time:selectedTime,endTime:addMinutes(selectedTime,selectedService.duration),price:selectedService.price,status:'pendente',createdAt:new Date().toISOString()};const cloud=await cloudCreateBooking(booking);if(!cloud.ok)return toast('Não foi possível reservar este horário. Escolha outro.');if(cloud.id)booking.id=cloud.id;const all=getBookings();all.push(booking);saveBookings(all);localStorage.setItem('sc_last_phone',phone);renderSuccess(booking);}
  function renderSuccess(b){set(`<div class="cv2-step-shell"><div class="cv2-success"><div class="cv2-success-icon">✓</div><div class="cv2-kicker">Solicitação enviada</div><h1 class="cv2-step-title">Agendamento recebido!</h1><p class="cv2-muted">O Studio irá confirmar seu horário.</p><div class="cv2-summary" style="text-align:left;margin-top:20px"><div class="cv2-summary-line"><span>Serviço</span><strong>${b.serviceName}</strong></div><div class="cv2-summary-line"><span>Data</span><strong>${fmtDate(b.date)}</strong></div><div class="cv2-summary-line"><span>Horário</span><strong>${b.time}</strong></div></div><div class="cv2-bottom-actions" style="position:static"><button class="cv2-back" onclick="cv2Nav('home')">Voltar ao início</button><button class="cv2-next" onclick="cv2Nav('bookings')">Ver meus agendamentos</button></div></div></div>`,'bookings')}
  function renderMyAppointments(){const phone=localStorage.getItem('sc_last_phone')||'';const mine=getBookings().filter(b=>!phone||b.phone===phone).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));const today=new Date().toISOString().slice(0,10),upcoming=mine.filter(b=>b.date>=today&&!['cancelado','recusado','concluido'].includes(b.status));set(`<section class="cv2-section"><div class="cv2-kicker">Sua agenda</div><h2>Meus agendamentos</h2><div class="cv2-tabs"><button class="active">Próximos</button><button onclick="cv2ShowHistory()">Histórico</button></div><div id="cv2Appointments">${upcoming.length?upcoming.map(appointmentCard).join(''):`<div class="cv2-empty"><strong>Você não tem agendamentos futuros.</strong><p>Escolha seu próximo cuidado com poucos toques.</p><button class="cv2-cta" onclick="cv2Nav('book')">Agendar agora</button></div>`}</div></section>`,'bookings');window.__cv2Mine=mine}
  function appointmentCard(b){const [y,m,d]=b.date.split('-');return `<div class="cv2-appointment"><div class="cv2-datebox"><small>${m}/${y}</small><strong>${d}</strong><span>${b.time}</span></div><div><strong>${b.serviceName}</strong><div class="cv2-muted">${b.professionalName||''}</div></div><span class="cv2-status ${b.status}">${typeof statusLabel==='function'?statusLabel(b.status):b.status}</span></div>`}
  window.cv2ShowHistory=()=>{const today=new Date().toISOString().slice(0,10),hist=(window.__cv2Mine||[]).filter(b=>b.date<today||['cancelado','recusado','concluido'].includes(b.status));document.getElementById('cv2Appointments').innerHTML=hist.length?hist.map(appointmentCard).join(''):'<div class="cv2-empty">Nenhum atendimento no histórico.</div>';document.querySelectorAll('.cv2-tabs button').forEach((b,i)=>b.classList.toggle('active',i===1))}
  function renderProfile(){set(`<section class="cv2-section" style="max-width:720px;margin-inline:auto"><div class="cv2-kicker">Conta</div><h2>Perfil do cliente</h2><div class="cv2-card cv2-form" style="margin-top:18px"><label>Nome</label><input placeholder="Seu nome"><label>Telefone</label><input value="${lastPhone}" placeholder="Seu WhatsApp"><label>E-mail</label><input type="email" placeholder="voce@email.com"><label>Data de nascimento</label><input type="date"><button class="cv2-next" style="margin-top:16px;width:100%;min-height:48px;border-radius:13px" onclick="toast('O cadastro de clientes será ativado em uma próxima etapa.')">Salvar perfil</button><div class="cv2-muted" style="margin-top:12px">O login e cadastro individual do cliente ainda não estão ativados no banco atual. A interface já está preparada para essa próxima etapa.</div></div></section>`,'profile')}
  if(typeof applyHomeImage==='function')try{applyHomeImage()}catch(e){}
  renderHome();
})();