(function(){
  function ensurePanel(id){const dash=document.getElementById('adminDashboard');if(!dash)return null;let p=document.getElementById(id);if(!p){p=document.createElement('div');p.id=id;p.className='admin-panel';dash.appendChild(p);}return p;}
  function addMenuItems(){const list=document.querySelector('#adminDrawer .admin-menu-list');if(!list)return;const agendaBtn=list.querySelector('[data-panel="agendaPanel"]');if(!agendaBtn)return;
    if(!list.querySelector('[data-panel="availabilityPanel"]')){const b=document.createElement('button');b.className='admin-menu-item';b.dataset.panel='availabilityPanel';b.innerHTML='<span class="admin-menu-icon">🗓️</span>Disponibilidade';b.onclick=()=>window.goAdminPanel?.('availabilityPanel');agendaBtn.insertAdjacentElement('afterend',b);}
    if(!list.querySelector('[data-panel="quickBookingPanel"]')){const ref=list.querySelector('[data-panel="availabilityPanel"]')||agendaBtn;const b=document.createElement('button');b.className='admin-menu-item';b.dataset.panel='quickBookingPanel';b.innerHTML='<span class="admin-menu-icon">⚡</span>Agendamento rápido';b.onclick=()=>window.goAdminPanel?.('quickBookingPanel');ref.insertAdjacentElement('afterend',b);}
  }
  function moveAvailability(){const p=ensurePanel('availabilityPanel');if(!p)return;let head=p.querySelector('.split-panel-head');if(!head){head=document.createElement('div');head.className='split-panel-head';head.innerHTML='<div class="section-kicker">Agenda</div><h2 class="section-title" style="margin-top:0">Disponibilidade</h2><p class="muted">Bloqueie dias ou horários em que o Studio não poderá receber agendamentos.</p>';p.prepend(head);}const mgr=document.getElementById('availabilityManager');if(mgr&&mgr.parentElement!==p)p.appendChild(mgr);}
  function moveQuickBooking(){const p=ensurePanel('quickBookingPanel');if(!p)return;let head=p.querySelector('.split-panel-head');if(!head){head=document.createElement('div');head.className='split-panel-head';head.innerHTML='<div class="section-kicker">Agenda</div><h2 class="section-title" style="margin-top:0">Agendamento rápido</h2><p class="muted">Cadastre manualmente um atendimento para a cliente.</p>';p.prepend(head);}const agenda=document.getElementById('agendaPanel');if(!agenda)return;const title=[...agenda.querySelectorAll('.section-title')].find(x=>x.textContent.trim()==='Agendamento rápido');if(title){const card=title.nextElementSibling;if(card&&card.classList.contains('card'))p.appendChild(card);title.remove();}}
  function cleanAgenda(){const p=document.getElementById('agendaPanel');if(!p)return;document.getElementById('dailySummary')?.remove();document.getElementById('adminAlerts')?.remove();document.getElementById('adminCalendar')?.remove();p.querySelector('.grid.two')?.remove();p.querySelector('.booking-filters')?.remove();p.querySelectorAll('.availability-manager').forEach(x=>{if(x.parentElement===p)moveAvailability();});const quickTitle=[...p.querySelectorAll('.section-title')].find(x=>x.textContent.trim()==='Agendamento rápido');if(quickTitle)moveQuickBooking();let title=[...p.querySelectorAll('.section-title')].find(x=>x.textContent.includes('Agenda de atendimentos'));if(title)title.textContent='Agendamentos confirmados';else if(!p.querySelector('.confirmed-only-title')){const h=document.createElement('div');h.className='confirmed-only-title';h.innerHTML='<div class="section-kicker">Agenda</div><h2 class="section-title" style="margin-top:0">Agendamentos confirmados</h2>';p.prepend(h);}}
  function renderConfirmedOnly(){try{adminBookingFilter='confirmado';}catch(e){}if(typeof renderAdmin==='function')renderAdmin();cleanAgenda();}
  const oldGo=window.goAdminPanel;
  if(oldGo&&!oldGo.__splitAgendaV43){const wrapped=function(id){if(id==='availabilityPanel'){ensurePanel('availabilityPanel');moveAvailability();}if(id==='quickBookingPanel'){ensurePanel('quickBookingPanel');moveQuickBooking();}if(id==='agendaPanel'){try{adminBookingFilter='confirmado';}catch(e){}}const r=oldGo.apply(this,arguments);if(id==='agendaPanel')setTimeout(renderConfirmedOnly,0);if(id==='availabilityPanel')setTimeout(()=>{moveAvailability();window.renderAvailabilityManager?.();},0);if(id==='quickBookingPanel')setTimeout(moveQuickBooking,0);return r;};wrapped.__splitAgendaV43=true;window.goAdminPanel=wrapped;}
  function patchRender(){if(typeof renderAdmin!=='function'||renderAdmin.__splitAgendaV43)return;const base=renderAdmin;const wrapped=function(){try{if(document.getElementById('agendaPanel')?.classList.contains('active'))adminBookingFilter='confirmado';}catch(e){}const r=base.apply(this,arguments);setTimeout(()=>{moveAvailability();moveQuickBooking();cleanAgenda();},0);return r;};wrapped.__splitAgendaV43=true;renderAdmin=wrapped;}
  function init(){ensurePanel('availabilityPanel');ensurePanel('quickBookingPanel');addMenuItems();patchRender();moveAvailability();moveQuickBooking();cleanAgenda();if(document.getElementById('agendaPanel')?.classList.contains('active'))renderConfirmedOnly();}
  setTimeout(init,900);setTimeout(init,1800);setTimeout(init,3200);
  const obs=new MutationObserver(()=>{addMenuItems();moveAvailability();moveQuickBooking();cleanAgenda();});obs.observe(document.body,{childList:true,subtree:true});setTimeout(()=>obs.disconnect(),10000);
})();