(function(){
  function ensurePanel(id){const dash=document.getElementById('adminDashboard');if(!dash)return null;let p=document.getElementById(id);if(!p){p=document.createElement('div');p.id=id;p.className='admin-panel';dash.appendChild(p);}return p;}
  function addMenuItems(){const list=document.querySelector('#adminDrawer .admin-menu-list');if(!list)return;const agendaBtn=list.querySelector('[data-panel="agendaPanel"]');if(!agendaBtn)return;if(!list.querySelector('[data-panel="availabilityPanel"]')){const b=document.createElement('button');b.className='admin-menu-item';b.dataset.panel='availabilityPanel';b.innerHTML='<span class="admin-menu-icon">🗓️</span>Disponibilidade';b.onclick=()=>window.goAdminPanel?.('availabilityPanel');agendaBtn.insertAdjacentElement('afterend',b);}if(!list.querySelector('[data-panel="quickBookingPanel"]')){const ref=list.querySelector('[data-panel="availabilityPanel"]')||agendaBtn;const b=document.createElement('button');b.className='admin-menu-item';b.dataset.panel='quickBookingPanel';b.innerHTML='<span class="admin-menu-icon">⚡</span>Agendamento rápido';b.onclick=()=>window.goAdminPanel?.('quickBookingPanel');ref.insertAdjacentElement('afterend',b);}}
  function moveAvailability(){const p=ensurePanel('availabilityPanel');if(!p)return;if(!p.querySelector('.split-panel-head')){const h=document.createElement('div');h.className='split-panel-head';h.innerHTML='<div class="section-kicker">Agenda</div><h2 class="section-title" style="margin-top:0">Disponibilidade</h2><p class="muted">Bloqueie dias ou horários em que o Studio não poderá receber agendamentos.</p>';p.prepend(h);}const mgr=document.getElementById('availabilityManager');if(mgr&&mgr.parentElement!==p)p.appendChild(mgr);}
  function moveQuickBooking(){const p=ensurePanel('quickBookingPanel');if(!p)return;if(!p.querySelector('.split-panel-head')){const h=document.createElement('div');h.className='split-panel-head';h.innerHTML='<div class="section-kicker">Agenda</div><h2 class="section-title" style="margin-top:0">Agendamento rápido</h2><p class="muted">Cadastre manualmente um atendimento para a cliente.</p>';p.prepend(h);}const agenda=document.getElementById('agendaPanel');if(!agenda)return;const title=[...agenda.querySelectorAll('.section-title')].find(x=>x.textContent.trim()==='Agendamento rápido');if(title){const card=title.nextElementSibling;if(card&&card.classList.contains('card'))p.appendChild(card);title.remove();}}
  function bookingCard(b){return `<div class="card booking-card" style="margin-bottom:12px"><div style="display:flex;justify-content:space-between;gap:12px"><div><strong>${fmtDate(b.date)} • ${b.time}</strong><div style="font-size:16px;margin-top:5px">${b.clientName||'Cliente'}</div><div class="muted">${b.serviceName||''}${b.professionalName?' • '+b.professionalName:''}</div><div class="muted">WhatsApp: ${b.phone||'-'}</div></div><div style="text-align:right"><strong>${money(Number(b.price||0))}</strong><br><span class="pill status-confirmado">Confirmado</span></div></div><div class="booking-actions"><button class="btn primary" onclick="setBookingStatus('${b.id}','concluido')">Marcar como concluído</button></div></div>`;}
  function renderConfirmedAppointments(){const p=document.getElementById('agendaPanel');if(!p)return;const confirmed=getBookings().filter(b=>b.status==='confirmado').sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time));p.innerHTML=`<div class="section-kicker">Agenda</div><h2 class="section-title" style="margin-top:0">Agendamentos confirmados</h2><p class="muted">Aqui aparecem somente os horários já confirmados com as clientes.</p><div id="adminBookings">${confirmed.length?confirmed.map(bookingCard).join(''):'<div class="card empty">Nenhum agendamento confirmado no momento.</div>'}</div>`;}
  const oldGo=window.goAdminPanel;if(oldGo&&!oldGo.__stableAppointmentsV55){const wrapped=function(id){if(id==='availabilityPanel'){ensurePanel('availabilityPanel');moveAvailability();}if(id==='quickBookingPanel'){ensurePanel('quickBookingPanel');moveQuickBooking();}const r=oldGo.apply(this,arguments);if(id==='agendaPanel')setTimeout(renderConfirmedAppointments,30);if(id==='availabilityPanel')setTimeout(()=>{moveAvailability();window.renderAvailabilityManager?.();},0);if(id==='quickBookingPanel')setTimeout(moveQuickBooking,0);return r;};wrapped.__stableAppointmentsV55=true;window.goAdminPanel=wrapped;}
  const oldRenderAdmin=window.renderAdmin||renderAdmin;if(oldRenderAdmin&&!oldRenderAdmin.__stableAppointmentsV55){const wrapped=function(){const r=oldRenderAdmin.apply(this,arguments);if(document.getElementById('agendaPanel')?.classList.contains('active'))setTimeout(renderConfirmedAppointments,0);return r;};wrapped.__stableAppointmentsV55=true;window.renderAdmin=wrapped;try{renderAdmin=wrapped;}catch(e){}}
  const oldSetStatus=window.setBookingStatus;if(oldSetStatus&&!oldSetStatus.__stableAppointmentsV55){const wrapped=async function(){const r=await oldSetStatus.apply(this,arguments);if(document.getElementById('agendaPanel')?.classList.contains('active'))setTimeout(renderConfirmedAppointments,30);return r;};wrapped.__stableAppointmentsV55=true;window.setBookingStatus=wrapped;}
  function init(){ensurePanel('availabilityPanel');ensurePanel('quickBookingPanel');addMenuItems();moveAvailability();moveQuickBooking();if(document.getElementById('agendaPanel')?.classList.contains('active'))renderConfirmedAppointments();}
  setTimeout(init,700);setTimeout(init,1600);setTimeout(init,2800);
  if(window.__ADMIN_ENTRY__){
    if(!document.querySelector('link[href*="admin-pro.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='admin-pro.css?v=57';document.head.appendChild(l);}
    const s=document.createElement('script');s.src='app23.js?v=57';document.body.appendChild(s);
  }
})();