let adminClients=[];
let clientSearch='';
function normalizePhone(v=''){return String(v).replace(/\D/g,'');}
function ensureClientsPanel(){const dashboard=document.getElementById('adminDashboard');if(!dashboard)return null;const tabs=dashboard.querySelector('.admin-tabs');let tab=[...tabs.querySelectorAll('button')].find(b=>b.textContent.trim()==='Clientes');if(!tab){tab=document.createElement('button');tab.textContent='Clientes';tab.setAttribute('onclick',"showAdminTab('clientsPanel',this);loadAdminClients()");tabs.appendChild(tab);}let panel=document.getElementById('clientsPanel');if(!panel){panel=document.createElement('div');panel.id='clientsPanel';panel.className='admin-panel';panel.innerHTML=`<div class="clients-head"><div><div class="section-kicker">Relacionamento</div><h2 class="section-title">Clientes</h2></div><span id="clientsCount" class="clients-count">0 clientes</span></div><div class="client-search-wrap"><input id="clientSearch" placeholder="Buscar por nome ou WhatsApp" oninput="filterAdminClients(this.value)" /></div><div id="clientsList" class="clients-list"><div class="card empty">Carregando clientes...</div></div><div id="clientDetail"></div>`;dashboard.appendChild(panel);}return panel;}
async function loadAdminClients(){ensureClientsPanel();if(!sb||!currentAdminUser)return;const {data,error}=await sb.from('clients').select('id,name,phone,email,notes,created_at').order('created_at',{ascending:false});if(error){toast('Não foi possível carregar os clientes.');return;}adminClients=data||[];renderAdminClients();}
function clientStats(client){const phone=normalizePhone(client.phone);const bookings=getBookings().filter(b=>normalizePhone(b.phone)===phone);const completed=bookings.filter(b=>b.status==='concluido');const total=completed.reduce((sum,b)=>sum+Number(b.price||0),0);const ordered=[...completed].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));return {bookings,completed,total,last:ordered[0]||null};}
function filterAdminClients(value){clientSearch=(value||'').toLowerCase().trim();renderAdminClients();}
function renderAdminClients(){const list=document.getElementById('clientsList');if(!list)return;const filtered=adminClients.filter(c=>!clientSearch||c.name.toLowerCase().includes(clientSearch)||normalizePhone(c.phone).includes(normalizePhone(clientSearch)));const count=document.getElementById('clientsCount');if(count)count.textContent=`${filtered.length} ${filtered.length===1?'cliente':'clientes'}`;list.innerHTML=filtered.length?filtered.map(c=>{const s=clientStats(c);return `<button class="client-card" onclick="openClientDetail('${c.id}')"><div class="client-avatar">${(c.name||'?').trim().charAt(0).toUpperCase()}</div><div class="client-card-main"><strong>${c.name}</strong><span>${c.phone}</span><small>${s.completed.length} ${s.completed.length===1?'atendimento concluído':'atendimentos concluídos'} • ${money(s.total)}</small></div><span class="client-card-arrow">›</span></button>`;}).join(''):'<div class="card empty">Nenhuma cliente encontrada.</div>';}
function openClientDetail(id){const c=adminClients.find(x=>x.id===id);if(!c)return;const s=clientStats(c),history=[...s.bookings].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));const phone=normalizePhone(c.phone),wa=phone.startsWith('55')?phone:'55'+phone;document.getElementById('clientDetail').innerHTML=`<div class="client-detail-card"><div class="client-detail-head"><div class="client-avatar large">${(c.name||'?').trim().charAt(0).toUpperCase()}</div><div><strong>${c.name}</strong><span>${c.phone}</span></div><button class="small-btn" onclick="closeClientDetail()">Fechar</button></div><div class="client-kpis"><div><small>Atendimentos</small><strong>${s.completed.length}</strong></div><div><small>Total gasto</small><strong>${money(s.total)}</strong></div><div><small>Último serviço</small><strong>${s.last?s.last.serviceName:'—'}</strong></div></div><div class="client-actions"><button class="btn secondary" onclick="window.open('https://wa.me/${wa}','_blank','noopener,noreferrer')">Abrir WhatsApp</button></div><label>Observações internas</label><textarea id="clientNotes">${c.notes||''}</textarea><button class="btn primary top-gap" onclick="saveClientNotes('${c.id}')">Salvar observações</button><h3 class="client-history-title">Histórico de atendimentos</h3><div class="client-history">${history.length?history.map(b=>`<div class="client-history-item"><div><strong>${fmtDate(b.date)} • ${b.time}</strong><span>${b.serviceName}</span></div><div><strong>${money(Number(b.price||0))}</strong><small>${statusLabel(b.status)}</small></div></div>`).join(''):'<div class="muted">Nenhum atendimento registrado.</div>'}</div></div>`;document.getElementById('clientDetail').scrollIntoView({behavior:'smooth',block:'start'});}
function closeClientDetail(){const el=document.getElementById('clientDetail');if(el)el.innerHTML='';}
async function saveClientNotes(id){if(!sb||!currentAdminUser){toast('Faça login.');return;}const notes=document.getElementById('clientNotes')?.value||'';const {error}=await sb.from('clients').update({notes}).eq('id',id);if(error){toast('Não foi possível salvar as observações.');return;}const c=adminClients.find(x=>x.id===id);if(c)c.notes=notes;toast('Observações da cliente salvas.');}
window.loadAdminClients=loadAdminClients;window.filterAdminClients=filterAdminClients;window.openClientDetail=openClientDetail;window.closeClientDetail=closeClientDetail;window.saveClientNotes=saveClientNotes;
const originalShowAdminDashboardClients=showAdminDashboard;showAdminDashboard=function(){originalShowAdminDashboardClients();ensureClientsPanel();setTimeout(loadAdminClients,150);};
setTimeout(()=>{ensureClientsPanel();if(currentAdminUser)loadAdminClients();},400);
