let adminClients=[];
let clientSearch='';
let clientReturnFilter='all';
function normalizePhone(v=''){return String(v).replace(/\D/g,'');}
function ensureClientsPanel(){const dashboard=document.getElementById('adminDashboard');if(!dashboard)return null;const tabs=dashboard.querySelector('.admin-tabs');let tab=[...tabs.querySelectorAll('button')].find(b=>b.textContent.trim()==='Clientes');if(!tab){tab=document.createElement('button');tab.textContent='Clientes';tab.setAttribute('onclick',"showAdminTab('clientsPanel',this);loadAdminClients()");tabs.appendChild(tab);}let panel=document.getElementById('clientsPanel');if(!panel){panel=document.createElement('div');panel.id='clientsPanel';panel.className='admin-panel';panel.innerHTML=`<div class="clients-head"><div><div class="section-kicker">Relacionamento</div><h2 class="section-title">Clientes</h2></div><span id="clientsCount" class="clients-count">0 clientes</span></div><div id="clientReturnSummary"></div><div class="client-search-wrap"><input id="clientSearch" placeholder="Buscar por nome ou WhatsApp" oninput="filterAdminClients(this.value)" /></div><div id="clientsList" class="clients-list"><div class="card empty">Carregando clientes...</div></div><div id="clientDetail"></div>`;dashboard.appendChild(panel);}return panel;}
async function loadAdminClients(){ensureClientsPanel();if(!sb||!currentAdminUser)return;const {data,error}=await sb.from('clients').select('id,name,phone,email,notes,created_at').order('created_at',{ascending:false});if(error){toast('Não foi possível carregar os clientes.');return;}adminClients=data||[];renderAdminClients();}
function clientStats(client){const phone=normalizePhone(client.phone);const bookings=getBookings().filter(b=>normalizePhone(b.phone)===phone);const completed=bookings.filter(b=>b.status==='concluido');const total=completed.reduce((sum,b)=>sum+Number(b.price||0),0);const ordered=[...completed].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));const last=ordered[0]||null;let daysSince=null;if(last){const a=new Date(last.date+'T12:00:00'),b=new Date(localISODate()+'T12:00:00');daysSince=Math.max(0,Math.floor((b-a)/86400000));}return {bookings,completed,total,last,daysSince};}
function filterAdminClients(value){clientSearch=(value||'').toLowerCase().trim();renderAdminClients();}
function setClientReturnFilter(filter){clientReturnFilter=filter;renderAdminClients();}
function clientReturnBand(days){if(days===null)return 'new';if(days>=90)return '90';if(days>=60)return '60';if(days>=30)return '30';return 'active';}
function renderClientReturnSummary(){const el=document.getElementById('clientReturnSummary');if(!el)return;const stats=adminClients.map(c=>clientStats(c));const c30=stats.filter(s=>s.daysSince!==null&&s.daysSince>=30&&s.daysSince<60).length,c60=stats.filter(s=>s.daysSince!==null&&s.daysSince>=60&&s.daysSince<90).length,c90=stats.filter(s=>s.daysSince!==null&&s.daysSince>=90).length;el.innerHTML=`<div class="return-summary"><div class="return-summary-head"><div><strong>Clientes para reativar</strong><span>Veja quem está há mais tempo sem voltar ao Studio.</span></div></div><div class="return-filter-grid"><button class="return-filter ${clientReturnFilter==='all'?'active':''}" onclick="setClientReturnFilter('all')"><small>Todas</small><strong>${adminClients.length}</strong></button><button class="return-filter ${clientReturnFilter==='30'?'active':''}" onclick="setClientReturnFilter('30')"><small>30–59 dias</small><strong>${c30}</strong></button><button class="return-filter ${clientReturnFilter==='60'?'active':''}" onclick="setClientReturnFilter('60')"><small>60–89 dias</small><strong>${c60}</strong></button><button class="return-filter ${clientReturnFilter==='90'?'active':''}" onclick="setClientReturnFilter('90')"><small>90+ dias</small><strong>${c90}</strong></button></div></div>`;}
function renderAdminClients(){const list=document.getElementById('clientsList');if(!list)return;renderClientReturnSummary();const filtered=adminClients.filter(c=>{const s=clientStats(c),band=clientReturnBand(s.daysSince);const matchSearch=!clientSearch||c.name.toLowerCase().includes(clientSearch)||normalizePhone(c.phone).includes(normalizePhone(clientSearch));const matchReturn=clientReturnFilter==='all'||band===clientReturnFilter;return matchSearch&&matchReturn;});const count=document.getElementById('clientsCount');if(count)count.textContent=`${filtered.length} ${filtered.length===1?'cliente':'clientes'}`;list.innerHTML=filtered.length?filtered.map(c=>{const s=clientStats(c),band=clientReturnBand(s.daysSince),inactive=s.daysSince!==null&&s.daysSince>=30;return `<button class="client-card ${inactive?'client-inactive':''}" onclick="openClientDetail('${c.id}')"><div class="client-avatar">${(c.name||'?').trim().charAt(0).toUpperCase()}</div><div class="client-card-main"><strong>${c.name}</strong><span>${c.phone}</span><small>${s.completed.length} ${s.completed.length===1?'atendimento concluído':'atendimentos concluídos'} • ${money(s.total)}</small>${s.last?`<em class="client-last ${inactive?'overdue':''}">${inactive?`${s.daysSince} dias sem voltar`:`Último atendimento há ${s.daysSince} dias`}</em>`:'<em class="client-last">Ainda sem atendimento concluído</em>'}</div>${inactive?`<span class="return-tag return-${band}">${band==='90'?'90+':band+' dias'}</span>`:''}<span class="client-card-arrow">›</span></button>`;}).join(''):'<div class="card empty">Nenhuma cliente encontrada neste filtro.</div>';}
function openClientDetail(id){const c=adminClients.find(x=>x.id===id);if(!c)return;const s=clientStats(c),history=[...s.bookings].sort((a,b)=>(b.date+b.time).localeCompare(a.date+a.time));const phone=normalizePhone(c.phone),wa=phone.startsWith('55')?phone:'55'+phone;const returnMsg=`Olá, ${c.name}! Tudo bem? Aqui é do Studio Capricho Hair 💛 Sentimos sua falta. Quando quiser cuidar do cabelo novamente, será um prazer te receber. Quer que eu veja os próximos horários disponíveis para você?`;document.getElementById('clientDetail').innerHTML=`<div class="client-detail-card"><div class="client-detail-head"><div class="client-avatar large">${(c.name||'?').trim().charAt(0).toUpperCase()}</div><div><strong>${c.name}</strong><span>${c.phone}</span>${s.daysSince!==null?`<small class="client-detail-return ${s.daysSince>=30?'attention':''}">Último atendimento há ${s.daysSince} dias</small>`:''}</div><button class="small-btn" onclick="closeClientDetail()">Fechar</button></div><div class="client-kpis"><div><small>Atendimentos</small><strong>${s.completed.length}</strong></div><div><small>Total gasto</small><strong>${money(s.total)}</strong></div><div><small>Último serviço</small><strong>${s.last?s.last.serviceName:'—'}</strong></div></div><div class="client-actions"><button class="btn secondary" onclick="window.open('https://wa.me/${wa}','_blank','noopener,noreferrer')">Abrir WhatsApp</button>${s.daysSince!==null&&s.daysSince>=30?`<button class="btn primary" onclick="window.open('https://wa.me/${wa}?text=${encodeURIComponent(returnMsg)}','_blank','noopener,noreferrer')">Convidar para voltar</button>`:''}</div><label>Observações internas</label><textarea id="clientNotes">${c.notes||''}</textarea><button class="btn primary top-gap" onclick="saveClientNotes('${c.id}')">Salvar observações</button><h3 class="client-history-title">Histórico de atendimentos</h3><div class="client-history">${history.length?history.map(b=>`<div class="client-history-item"><div><strong>${fmtDate(b.date)} • ${b.time}</strong><span>${b.serviceName}</span></div><div><strong>${money(Number(b.price||0))}</strong><small>${statusLabel(b.status)}</small></div></div>`).join(''):'<div class="muted">Nenhum atendimento registrado.</div>'}</div></div>`;document.getElementById('clientDetail').scrollIntoView({behavior:'smooth',block:'start'});}
function closeClientDetail(){const el=document.getElementById('clientDetail');if(el)el.innerHTML='';}
async function saveClientNotes(id){if(!sb||!currentAdminUser){toast('Faça login.');return;}const notes=document.getElementById('clientNotes')?.value||'';const {error}=await sb.from('clients').update({notes}).eq('id',id);if(error){toast('Não foi possível salvar as observações.');return;}const c=adminClients.find(x=>x.id===id);if(c)c.notes=notes;toast('Observações da cliente salvas.');}
window.loadAdminClients=loadAdminClients;window.filterAdminClients=filterAdminClients;window.setClientReturnFilter=setClientReturnFilter;window.openClientDetail=openClientDetail;window.closeClientDetail=closeClientDetail;window.saveClientNotes=saveClientNotes;
const originalShowAdminDashboardClients=showAdminDashboard;showAdminDashboard=function(){originalShowAdminDashboardClients();ensureClientsPanel();setTimeout(loadAdminClients,150);};
setTimeout(()=>{ensureClientsPanel();if(currentAdminUser)loadAdminClients();},400);
